
PROCESS BEFORE OUTPUT.

  MODULE status_2200.

*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TCONT'
  MODULE tcont_change_tc_attr.
*&SPWIZARD: MODULE TCONT_CHANGE_COL_ATTR.
  LOOP AT   t9951
       INTO t9951
       WITH CONTROL tcont
       CURSOR tcont-current_line.
*&SPWIZARD:   MODULE TCONT_CHANGE_FIELD_ATTR
  ENDLOOP.


PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TCONT'
  LOOP AT t9951.
    CHAIN.
      FIELD t9951-begda.
      FIELD t9951-odmtr.
      FIELD t9951-acikl.
      FIELD t9951-manue.
    ENDCHAIN.
    FIELD t9951-field
      MODULE tcont_mark ON REQUEST.
  ENDLOOP.
*&SPWIZARD: MODULE TCONT_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TCONT_CHANGE_COL_ATTR.


  MODULE user_command_2200.
