*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 27.01.2022 at 17:16:32
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZHRBR_V004......................................*
FORM GET_DATA_ZHRBR_V004.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHRBR_T004 WHERE
(VIM_WHERETAB) .
    CLEAR ZHRBR_V004 .
ZHRBR_V004-MANDT =
ZHRBR_T004-MANDT .
ZHRBR_V004-ORNGR =
ZHRBR_T004-ORNGR .
ZHRBR_V004-BUKRS =
ZHRBR_T004-BUKRS .
ZHRBR_V004-LGART =
ZHRBR_T004-LGART .
ZHRBR_V004-BEGDA =
ZHRBR_T004-BEGDA .
ZHRBR_V004-ENDDA =
ZHRBR_T004-ENDDA .
ZHRBR_V004-LGART_NT =
ZHRBR_T004-LGART_NT .
ZHRBR_V004-ISLEM =
ZHRBR_T004-ISLEM .
<VIM_TOTAL_STRUC> = ZHRBR_V004.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHRBR_V004 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHRBR_V004.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHRBR_V004-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHRBR_T004 WHERE
  ORNGR = ZHRBR_V004-ORNGR AND
  BUKRS = ZHRBR_V004-BUKRS AND
  LGART = ZHRBR_V004-LGART AND
  BEGDA = ZHRBR_V004-BEGDA .
    IF SY-SUBRC = 0.
    DELETE ZHRBR_T004 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHRBR_T004 WHERE
  ORNGR = ZHRBR_V004-ORNGR AND
  BUKRS = ZHRBR_V004-BUKRS AND
  LGART = ZHRBR_V004-LGART AND
  BEGDA = ZHRBR_V004-BEGDA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHRBR_T004.
    ENDIF.
ZHRBR_T004-MANDT =
ZHRBR_V004-MANDT .
ZHRBR_T004-ORNGR =
ZHRBR_V004-ORNGR .
ZHRBR_T004-BUKRS =
ZHRBR_V004-BUKRS .
ZHRBR_T004-LGART =
ZHRBR_V004-LGART .
ZHRBR_T004-BEGDA =
ZHRBR_V004-BEGDA .
ZHRBR_T004-ENDDA =
ZHRBR_V004-ENDDA .
ZHRBR_T004-LGART_NT =
ZHRBR_V004-LGART_NT .
ZHRBR_T004-ISLEM =
ZHRBR_V004-ISLEM .
    IF SY-SUBRC = 0.
    UPDATE ZHRBR_T004 .
    ELSE.
    INSERT ZHRBR_T004 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHRBR_V004-UPD_FLAG,
STATUS_ZHRBR_V004-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZHRBR_V004.
  SELECT SINGLE * FROM ZHRBR_T004 WHERE
ORNGR = ZHRBR_V004-ORNGR AND
BUKRS = ZHRBR_V004-BUKRS AND
LGART = ZHRBR_V004-LGART AND
BEGDA = ZHRBR_V004-BEGDA .
ZHRBR_V004-MANDT =
ZHRBR_T004-MANDT .
ZHRBR_V004-ORNGR =
ZHRBR_T004-ORNGR .
ZHRBR_V004-BUKRS =
ZHRBR_T004-BUKRS .
ZHRBR_V004-LGART =
ZHRBR_T004-LGART .
ZHRBR_V004-BEGDA =
ZHRBR_T004-BEGDA .
ZHRBR_V004-ENDDA =
ZHRBR_T004-ENDDA .
ZHRBR_V004-LGART_NT =
ZHRBR_T004-LGART_NT .
ZHRBR_V004-ISLEM =
ZHRBR_T004-ISLEM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHRBR_V004 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHRBR_V004-ORNGR TO
ZHRBR_T004-ORNGR .
MOVE ZHRBR_V004-BUKRS TO
ZHRBR_T004-BUKRS .
MOVE ZHRBR_V004-LGART TO
ZHRBR_T004-LGART .
MOVE ZHRBR_V004-BEGDA TO
ZHRBR_T004-BEGDA .
MOVE ZHRBR_V004-MANDT TO
ZHRBR_T004-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHRBR_T004'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHRBR_T004 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHRBR_T004'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
